xenon-ssh:
  image: nlesc/xenon-ssh
# For ssh gateway tests
xenon-ssh2:
  image: nlesc/xenon-ssh
  links:
    - xenon-ssh
xenon-ftp:
  image: nlesc/xenon-ftp
xenon-torque:
  image: nlesc/xenon-torque
  cap_add:
    - SYS_RESOURCE
# Slurm stores accounting in MySQL
mysql:
  image: mysql:5.5
  environment:
  - MYSQL_ROOT_PASSWORD=xenon-slurm-pw
xenon-slurm:
  image: nlesc/xenon-slurm
  links:
  - mysql
xenon-webdav:
  image: nlesc/xenon-webdav
xenon-gridengine:
  image: nlesc/xenon-gridengine
# TODO Docker test on travis-ci can not run multi host gridengine due hostname resolving errors
#xenon-gridengine-exec1:
#  image: nlesc/xenon-gridengine-exec
#  volumes_from:
#    - xenon-gridengine
#  links:
#    - xenon-gridengine
xenon-test:
  image: nlesc/xenon-test
  volumes:
    - ../../..:/code
  environment:
    - MYUID
  command: ./gradlew -Pxenon.test.properties=src/integrationTest/docker/xenon.test.properties.docker --stacktrace --project-cache-dir /home/xenon/gradle-cache integrationTest
  links:
    - xenon-ssh
    - xenon-ssh2
    - xenon-ftp
    - xenon-webdav
    - xenon-torque
    - xenon-slurm
    - xenon-gridengine
#    - xenon-gridengine-exec1
