language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk10
      env:
        - INTEGRATION_TEST="integration"
        - JDK=oraclejdk10
        - OS=linux
      sudo: true
      dist: trusty
      services:
        - docker
      addons:
        sonarqube:
          organization: nlesc
      before_install:
        - docker-compose --version
      script:
        - ./gradlew check
        - ./src/fixedClientEnvironmentTest/resources/run-fixed-client-environment-test.sh;
      after_script:
        - ./gradlew jacocoIntegrationTestReport jacocoFixedClientEnvironmentTestReport;
        - bash <(curl -s https://codecov.io/bash) -e JDK,OS -F unit -f build/reports/jacoco/test/jacocoTestReport.xml;
        - bash <(curl -s https://codecov.io/bash) -e JDK,OS -F integration -f build/reports/jacoco/jacocoIntegrationTestReport/jacocoIntegrationTestReport.xml;
        - bash <(curl -s https://codecov.io/bash) -e JDK,OS -F fixedclientenvironment -f build/reports/jacoco/jacocoFixedClientEnvironmentTestReport/jacocoFixedClientEnvironmentTestReport.xml;
        - sonar-scanner -Dsonar.login=$SONAR_TOKEN;

    - os: osx
      env:
        - INTEGRATION_TEST="livelocal"
        - JDK=oraclejdk10
        - OS=osx
      osx_image: xcode9
      script:
        - ./src/liveTest/resources/scripts/create_symlinks;
        - ./gradlew test liveTest -Dxenon.scheduler=local -Dxenon.filesystem=file -Dxenon.filesystem.location=/ -Dxenon.scheduler.location=$PWD -Dxenon.username=$USERNAME -Dxenon.filesystem.basedir=$PWD -Dxenon.filesystem.expected.workdir=/ -Dxenon.scheduler.workdir=$PWD -Dxenon.scheduler.supportsInteractive=1 -Dxenon.scheduler.isEmbedded=1
      after_script:
       -  ./gradlew jacocoTestReport jacocoLiveTestReport
       - bash <(curl -s https://codecov.io/bash) -e JDK,OS -F unit -f build/reports/jacoco/test/jacocoTestReport.xml;
       - bash <(curl -s https://codecov.io/bash) -e JDK,OS -F livelocal -f build/reports/jacoco/jacocoLiveTestReport/jacocoLiveTestReport.xml
  fast_finish: true


install:
  - ./gradlew assemble
