version: '{branch}-{build}'
environment:
  JAVA_HOME: C:\Program Files\Java\jdk10
build_script:
  - SET "PATH=%JAVA_HOME%\bin;%PATH%"
  - javac -version
  - java -version
  - cmd: ./gradlew.bat clean assemble
test_script:
  - SET "PATH=%JAVA_HOME%\bin;%PATH%"
  - mkdir build\integrationTest & cd build\integrationTest & ..\..\src\liveTest\resources\scripts\create_symlinks.bat & cd ..\..
  - cmd: gradlew.bat test liveTest -Dxenon.scheduler=local -Dxenon.scheduler.location=%HomeDrive%\projects\xenon -Dxenon.filesystem=file -Dxenon.filesystem.location=%HomeDrive%\projects\xenon -Dxenon.username=%USERNAME% -Dxenon.filesystem.basedir=\projects\xenon\build\integrationTest -Dxenon.separator=\ -Dxenon.filesystem.expected.workdir=\projects\xenon -Dxenon.scheduler.workdir=\projects\xenon -Dxenon.scheduler.supportsInteractive=1 -Dxenon.scheduler.isEmbedded=1
on_finish:
  - SET "PATH=%JAVA_HOME%\bin;%PATH%"
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - "SET JDK=openjdk10"
  - .\gradlew.bat jacocoTestReport jacocoLiveTestReport
  - pip install codecov
  - codecov -e OS,JDK -F unit -f build/reports/jacoco/test/jacocoTestReport.xml
  - ps: |
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      Get-ChildItem "build/test-results/test/" -Filter *.xml | Foreach-Object{
        (New-Object 'System.Net.WebClient').UploadFile($url, $_.FullName)
      }
  - codecov -e OS,JDK,INTEGRATION_TEST -F livelocal -f build/reports/jacoco/jacocoLiveTestReport/jacocoLiveTestReport.xml
  - ps: |
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      Get-ChildItem "build/test-results/liveTest/" -Filter *.xml | Foreach-Object{
        (New-Object 'System.Net.WebClient').UploadFile($url, $_.FullName)
      }
artifacts:
  - path: build/distributions/*.zip
    name: Java archive
