# Site settings
title: Xenon by NLeSC
description: > # this means to ignore newlines until "baseurl:"
  A middleware abstraction library that provides a simple programming interface
  to various compute and storage resources.
baseurl: "/Xenon/" # the subpath of your site, e.g. /blog/
url: "http://nlesc.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
keep_files:
- versions
timezone: UTC
